### ISSUE TITLE
Фронт работ на второй день соревнования

### ISSUE THREAD

**Issue by Minoru** [codingteam/icfpc-2020#1]
Итак, за пятницу мы:
1. написали «упрощалку» выражений, поддерживающую все операторы из data/galaxy.txt. Код в уже в master (src/ и test/).
2. предприняли пару попыток вручную оттранслировать data/galaxy.txt в какой-нибудь ЯП и запустить, но:
    - Haskell не может вывести типы (они получаются бесконечными из-за рекурсивных выражений)
    - Racket не может понять, что объявляемая функция каррирована. Наработки лежат в master в transpiler/, Портнов сказал, что транспайлер можно доделать, чтобы он добавлял к объявлениям функций именованные аргументы и таким образом помогал интерпретатору разобраться в коде.

В процессе:
- unclechu пишет биндинги к [API](https://icfpc2020-api.testkontur.ru/swagger/index.html)
- pink-snow думает над тем, как вычислять описанную в data/galaxy.txt программу:
    - galaxy ссылается на другие функции, поэтому её нельзя скормить reducer-у — нужна какая-то функция, которая будет подставлять в galaxy константы
    - в data/galaxy.txt есть рекурсивные определения, поэтому подставлять нужно как-то хитро — не всё сразу, а пошагово, в надежде, что программа в итоге сойдётся к чему-то поменьше

Что (по моему мнению) нужно сделать в ближайшее время:
1. **добавить в reducer поддержку всех остальных функций (кроме send).** Судя по сообщениям [42](https://message-from-space.readthedocs.io/en/latest/message42.html), [38](https://message-from-space.readthedocs.io/en/latest/message38.html) и [39](https://message-from-space.readthedocs.io/en/latest/message39.html), мы должны играть с инопланетянами в какую-то игру. Нужен вывод доски хотя бы в виде ASCII;
2. **имея фичастый reducer и eval от pink-snow, посмотреть на визуализацию протокола из сообщения [40](https://message-from-space.readthedocs.io/en/latest/message40.html)**. Фактически это отладка: первые шаги должны совпадать с теми, что показаны в сообщениях;
3. **используя AlienAPI, реализовать send (сообщение [15](https://message-from-space.readthedocs.io/en/latest/message15.html)) и для отладки запустить сообщение [41](https://message-from-space.readthedocs.io/en/latest/message41.html);**
4. **запустить galaxy с nil и (0,0), как описано в [39](https://message-from-space.readthedocs.io/en/latest/message39.html)**

**Comment by Minoru** [comment]
Логи конференции: https://debiania.in.ua/tmp/icfpc-codingteam.log.txt

**Comment by IngvarJackal** [comment]
Визуализированный с помощью [galaxy.py](https://github.com/Minoru/icfpc-2020/blob/master/transpiler/galaxy.py) граф зависимостей между функциями, где жёлтые функции не имеют зависимостей, красная -- galaxy, а размер остальных зависит от количества внешних зависимостей.
Также скрипт содержит независимую попытку создать интерпретатор команд.
![](https://github.com/Minoru/icfpc-2020/raw/master/transpiler/galaxy.gv.png)
